// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Invalid log in', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Invalid log in', async function() {
    await driver.get("https://www.bonapp.app/Identity/Account/Login")
    await driver.manage().window().setRect({ width: 1280, height: 672 })
    await driver.findElement(By.id("emailInput")).click()
    await driver.findElement(By.id("emailInput")).sendKeys("pilpuka.katija@gmail.com")
    await driver.findElement(By.id("passwordInput")).click()
    await driver.findElement(By.id("passwordInput")).sendKeys("kakakaka")
    await driver.findElement(By.id("login-submit")).click()

    // Wait for the element to appear
    await driver.wait(until.elementLocated(By.css('.text-danger.loginValidation.validation-summary-errors')), 10000);

    // Find the element
    const validationElement = await driver.findElement(By.css('.text-danger.loginValidation.validation-summary-errors'));

    // Assert that the element is displayed
    const isDisplayed = await validationElement.isDisplayed();
    assert.strictEqual(isDisplayed, true, "Validation message is not displayed");
  })
})
