// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('test 1', async function() {
    await driver.get("https://bonapp.app/")
    await driver.manage().window().setRect({ width: 1578, height: 968 })
    await driver.findElement(By.css(".single-restaurant:nth-child(6) .card-body")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.id("customerLink")).click()
    vars["win4413"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win4413"])
    await driver.findElement(By.css("#\\32 826 .product-description:nth-child(3)")).click()
    await driver.findElement(By.css(".addOnContainer:nth-child(1)")).click()
    await driver.findElement(By.css(".mt-0 > .col-12")).click()
    await driver.findElement(By.css(".col-12")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".dark-green-bg:nth-child(1)")).click()
    await driver.findElement(By.id("emailInput")).click()
    await driver.findElement(By.id("emailInput")).sendKeys("test@test.com")
    await driver.findElement(By.css(".w-100:nth-child(4) > .col-12")).click()
    await driver.switchTo().window(vars["root"])
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.id("kitchenLink")).click()
    vars["win2214"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win2214"])
    await driver.findElement(By.css(".fa-circle-check > path")).click()
  })
})
